### ISSUE TITLE
Types for files

### ISSUE THREAD

**Issue by madsh93** [maltejur/directus-extension-generate-types#1]
Hi!

Thank you so much for this module. It's really nice and makes the development experience even better when working with Directus.

I was just wondering if it makes sense to include the nested level of files/images in the typescript generator. Or maybe make it a configuration.

A simple collection in Directus looks like this:

title: string
image: file

the API would return:

title: 'Lorem Ipsum',
image: '0627d8ff-d9fb-4809-a54d-775778713267'

But when working with images/files in Directus I always have to get the nested level, in order to get the extension or filename_disk in order to provide the correct link to the file/image.

**Comment by madsh93** [comment]
Nevermind.. I see that you actually include system types.. All good.

**Comment by feliche93** [comment]
@madsh93 how were you able to get the nested type? When I query let's say `image.*` typescript says `image.id` is invalid. Do you have a code snippet you could share?
