### ISSUE TITLE
Field with dash results in wrong ts file

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [maltejur/directus-extension-generate-types#10]
Example:
By creating a directus notice filed, directus automaticly uses a name like: "notice-siuefhs".
This results at the export to:

<img width="485" alt="Bildschirmfoto 2022-09-23 um 16 36 08" src="https://user-images.githubusercontent.com/33295329/191985672-544aab16-41da-4d7c-81f9-93dc0885d365.png">

Which is an incorrect typescript file.

**Comment by maltejur** [comment]
Thanks for the bug report, should be fixed in v0.3.1
