### ISSUE TITLE
module is not displayed

### ISSUE THREAD

**Issue by Bloggerschmidt** [maltejur/directus-extension-generate-types#13]
I copied the file `index.js` into the directory `extensions/modules/generate-types/` and went to `admin/settings/project`. Unfortunately no Module is displayed to activate. I'm using directus 9.18.1. The rights of folder and file are the same as for others. What could be possible wrong? Thanks for every hint!

**Comment by maltejur** [comment]
Does the same issue happen with this release? https://github.com/maltejur/directus-extension-generate-types/releases/tag/0.3.0

**Comment by Bloggerschmidt** [comment]
It works with release 0.3.1. I had to restart the server. Thanks for your fast reply and of course, this great extension. Very helpful!
