### ISSUE TITLE
Folders get exported as empty objects

### ISSUE THREAD

**Issue by badrange** [maltejur/directus-extension-generate-types#15]
In our project we have a folder called "Content" that gets exported as a type which causes a warning from our eslint:

`export type Content = {};` 

> Don't use `{}` as a type. `{}` actually means "any non-nullish value".

I think it would be great if the extension skips these folders too?

Related to #11

**Comment by maltejur** [comment]
Fixed in https://github.com/maltejur/directus-extension-generate-types/commit/236f82a32ecca6174c7742a39b3deee8a61dca36

**Comment by badrange** [comment]
Great, thank you!
