### ISSUE TITLE
Hide module for non-admins

### ISSUE THREAD

**Issue by Dominic-Marcelino** [maltejur/directus-extension-generate-types#20]
Currently everyone can see the module. As this module is only required for devs and a dev will most likely have admin access, I'd suggest to limit the visibility to admin-users. 

Fore sure there's probably use-cases where devs aren't admin, but that's probably less often the case than non-devs that see the module.

Not 100% sure about the implementation, but it should be possible to fetch the user before the export and then set the visibility based on the users role

https://github.com/maltejur/directus-extension-generate-types/blob/4acb6f012f21ab6203d30fc43e803d49b01280c5/src/index.ts#L40

**Comment by maltejur** [comment]
I think there is an even easier way to do this. There is a more or less undocumented method that checks if the current user should be able to use the extension: https://github.com/maltejur/directus-extension-generate-types/commit/950d8b3e63138e2945b5c0101561293986b4bc69
