### ISSUE TITLE
Doesn't seem to work with directus 10.10.4

### ISSUE THREAD

**Issue by navanshu** [maltejur/directus-extension-generate-types#38]
The extension was working fine before this, but on this version it doesn't even show up in the settings

**Comment by ThomasMoritz** [comment]
I had the same problem and had to do the following steps to bring it up again after the "old" extension structure was deprecated some releases ago.

1. Under the `extension` folder I created a `directus-extension-generate-types` folder
2. I put the `package.json` from this repository into the `directus-extension-generate-types` folder
3. I created a `dist` folder under `directus-extension-generate-types` and copied the `index.js` into it

After that everything worked as expected...

**Comment by SvenBudak** [comment]
i can confirm that it is not working on 10.10.5.. 
@maltejur you have plans to update this package to latest directus?

**Comment by ThomasMoritz** [comment]
If you copy the extension into the right directory and add the package.json next to the JS file it works on the latest version.

**Comment by SvenBudak** [comment]
> If you copy the extension into the right directory and add the package.json next to the JS file it works on the latest version.

but if i understand it correctly, directus expect now all extentions in the root folder right? because you said "in the extentions folder"

**Comment by ThomasMoritz** [comment]
@SvenBudak So I just checked our installation. 
I put the `package.json` into `extensions/directus-extension-generate-types` and the 'index.js' into  `extensions/directus-extension-generate-types/dist` . The `package.json` is exactly this one https://github.com/maltejur/directus-extension-generate-types/blob/master/package.json

**Comment by SvenBudak** [comment]
![image](https://github.com/maltejur/directus-extension-generate-types/assets/4930169/bc083a94-6f93-41af-983a-c313624e3237)
not working for me, i just get this "missing" thing with the cryptic id

**Comment by HadiSDev** [comment]
In my situation it is installed but I dont have the side menu button:
![image](https://github.com/maltejur/directus-extension-generate-types/assets/10367624/ea22053f-25ea-42d1-bb97-71bd1904e459)

**Comment by maltejur** [comment]
I haven't updated the readme yet but you can also just install the addon through the new extensions marketplace:

![image](https://github.com/maltejur/directus-extension-generate-types/assets/48161361/b5a8b573-4b4e-4d48-9822-04344f9d57af)

**Comment by maltejur** [comment]
@HadiSDev 

> In my situation it is installed but I dont have the side menu button

You are probably missing this step:

> Go into the Project Settings of your directus project (/admin/settings/project) and enable the Generate Types module at the bottom of the page.

**Comment by izoukhai** [comment]
With 10.10.7, installing manually with the dist/index.js & package.json or installing through marketplace doesn't work anymore.

The extension is correctly installed, but in the Project Settings, I cannot find the extension anymore

**Comment by hjopel** [comment]
> With 10.10.7, installing manually with the dist/index.js & package.json or installing through marketplace doesn't work anymore.
> 
> The extension is correctly installed, but in the Project Settings, I cannot find the extension anymore

I'm using 10.10.7 and for me, after installing it from the marketplace, I just had to check it under admin/settings/project - "Modules":

![image](https://github.com/maltejur/directus-extension-generate-types/assets/70332133/5f275c01-d731-4eb1-8193-129812a5b6bd)
