### ISSUE TITLE
Not working after upgrade to Directus 11.0.1

### ISSUE THREAD

**Issue by keesvanbemmel** [maltejur/directus-extension-generate-types#40]
Hi there,

it seems like the module is not loading in Directus 11.0.1 even though the extension is installed and enabled. It doesn't list in the settings screen though for me to enable it in the sidebar.

Anyone know how to fix this?

Cheers!

Kees.

**Comment by keesvanbemmel** [comment]
Fix described here: https://github.com/directus/directus/issues/23307#issuecomment-2284451603

**Comment by jeronimoek-binpar** [comment]
> Fix described here: [directus/directus#23307 (comment)](https://github.com/directus/directus/issues/23307#issuecomment-2284451603)

How did you fix it?

**Comment by tresorama** [comment]
I cannot understand which manual intervention we need to make to fix that the extension icon is not showing.
Someone can point me in the right direction ??

Directus: 11.1.1
Extension: 0.6.1
Installed via: Marketplace
